module Try1

	use import int.Int
	use import ref.Ref

	exception Myexc int
	let b(x:int) : int
	ensures { result = 10 }
	=
		let i = ref 0 in
		i := 0;
		while !i < 10 do
			variant { 10 - !i  }
			try
			raise (Myexc (!i + 1));
			i := !i - 1;
			with
			| Myexc(a) -> i := a
			end
		done;
		!i
end
